name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure it's just 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy site files to public
        run: |
          mkdir public
          cp shop.html public/index.html  # Copy shop.html as index.html
          cp -r css js assets public/     # Copy all necessary folders

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
