name: Deploy to GitHub Pages

on:
  push:
    branches: github.com/HozaifaDev/PUA-E-Commerce/

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build static files
        run: |
          mkdir public
          echo "Hello World!" > public/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
